require "autodiscover/version"
require "nokogiri"
require "nori"
require "httpclient"
require "logging"
require "autodiscover/errors"
require "autodiscover/client"
require "autodiscover/pox_request"
require "autodiscover/pox_response"
require "autodiscover/server_version_parser"
require "autodiscover/logging"

